; Script for PromptPlus Installer
; Generated by Gemini Assistant

#define MyAppName "PromptPlus"
#define MyAppVersion "0.1"
#define MyAppPublisher "Edis Aganovic"
#define MyAppURL "https://www.edu387.com"
#define MyAppExeName "PromptPlus.exe"
#define MyAppIcoName "icon.ico"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C9F4E3A1-2B4D-4E1F-9A3C-5D6E7F8G9H0I}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; The [Icons] section uses this to create the shortcut
OutputBaseFilename=PromptPlus_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Output directory for the installer exe
OutputDir=dist
; Icon for the installer file itself (optional, uses default if not specified)
SetupIconFile=icon.ico
; Uninstall settings
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; The source directory is 'dist\PromptPlus' which is generated by the PyInstaller build
Source: "dist\PromptPlus\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppIcoName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppIcoName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent
